import '../sass/index.scss';

import Head from "next/head";
import type { AppProps } from 'next/app'
import Layout from '../components/Layout'

function MyApp({ Component, pageProps }: AppProps) {
  return(
    <Layout>
      <Head>
        <title>rice kasa bazar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/rice.png" />
        <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;500;600;700&amp;family=Sora:wght@200;300;400;500;600;700&amp;display=swap" rel="stylesheet" />
      </Head>
      <Component {...pageProps} />
    </Layout>
  )
  
}

export default MyApp
